### ISSUE TITLE
Logging actions in the renderer process

### ISSUE THREAD

**Issue by alexemorris** [hardchor/electron-redux#12]
(repost of original question on electron boilerplate repo discussion)

I've looked through your time sheets repo and I have now implemented in a similar way using this module and its working great!

I'm just struggling and also unsure if there is any way of having actions dispatched in the main process appear in the dev tools or any log of them whatsoever, they appear to be firing and updating state, but I have no way of tracking what actions have and haven't been sent!
Alex

**Comment by hardchor** [comment]
Hey,

https://github.com/hardchor/timesheets/blob/master/app/main/tasks/osxAutoUpdater.js#L27 is an example on how to dispatch actions from the main process. There should be nothing that stops them from being replayed to the renderer stores though.

Are you saying that they aren't?

**Comment by alexemorris** [comment]
Ok, I think it was because I was configuring the stores wrong. I am trying to combine the configurestore.development.js from the electron redux boilerplate (including the composeEnhancers method of hooking in the dev tools) and your configure store method from time sheets.

You have a slightly different implementation in the time sheets repo than is recommended in your readme as I think you are using a version that was before you developed it as a standalone package which makes it a little tougher to follow. 

Here is my configure store, it it not working and prevents the app from launching but I think it is almost there, I just can't seem to figure out the problem. 




`
import { createStore, applyMiddleware, compose } from 'redux';
import { forwardToMain, forwardToRenderer, triggerAlias, replayActionMain, replayActionRenderer, } from 'electron-redux';
import { hashHistory } from 'react-router';
import { routerMiddleware, push } from 'react-router-redux';
import createLogger from 'redux-logger';
import thunk from 'redux-thunk';
import promise from 'redux-promise';
import getRootReducer from '../reducers';

import * as templatorActions from '../actions/templator';
import * as inputActions from '../actions/inputs';
import * as mappingActions from '../actions/mappings';
import * as locationsActions from '../actions/locations';
import * as defaultsActions from '../actions/defaults';

export default function configureStore(initialState, scope = 'main') {
  const actionCreators = {
    ...templatorActions,
    ...inputActions,
    ...mappingActions,
    ...locationsActions,
    ...defaultsActions,
    push,
  };

  const logger = createLogger({
    level: 'info',
    collapsed: true
  });

  const router = routerMiddleware(hashHistory);

  let middleware = [
    thunk,
    promise,
  ];

  if (!process.env.NODE_ENV) {
    middleware.push(logger);
  }

  let enhancer;

  if (scope === 'renderer') {
    middleware = [
      forwardToMain,
      router,
      ...middleware,
    ];

    const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
        // Options: http://zalmoxisus.github.io/redux-devtools-extension/API/Arguments.html
        actionCreators,
      }) : compose;

    enhancer = compose(...[applyMiddleware(...middleware)]);
  } else {
    middleware = [
      triggerAlias,
      ...middleware,
      forwardToRenderer,
    ];

    enhancer = compose(...[applyMiddleware(...middleware)]);
  }

  const rootReducer = getRootReducer(scope);
  const store = createStore(rootReducer, initialState, enhancer);

  if (!process.env.NODE_ENV && module.hot) {
    module.hot.accept('../reducers', () =>
      store.replaceReducer(require('../reducers')) // eslint-disable-line global-require
    );
  }

  if (scope === 'main') {
    replayActionMain(store);
  } else {
    replayActionRenderer(store);
  }

  return store;
}
`

**Comment by alexemorris** [comment]
I think the main problem here is I'm not entirely sure what half of the above code is actually doing!

**Comment by alexemorris** [comment]
FIXED IT, no idea what the problem was, fixed its self. As for the original issue with the logger, I've been staring at this for 3 hours. I was calling the actions before the window was shown, so the store was correct but it wasn't showing up in the log!

**Comment by hardchor** [comment]
Hey,

Glad you fixed it! I decided to change `configureStore` because it was unnecessarily complex (and 2 separate files for dev and prod despite very little difference). I also changed a fair bit of the app structure, which might serve as inspiration on how slightly bigger apps could look like.

**Comment by hardchor** [comment]
Re: the difference in implementation. The README only demonstrates a very basic store setup (I actually took that from the redux docs).

**Comment by alexemorris** [comment]
Perfect, thank you. The timesheets repo has been highly useful! 

Just a quick question about your implementation, my app is being used to manipulate a fairly large dataset, which requires storing a large chunk of the data in the state object. Would this and/or using redux cause the app to slow down when my state is pretty huge (say 25/50/100mb)?

I'm asking because its noticeably slower to dispatch actions when the data is loaded compared to when its not. I'm not sure if this is a redux problem, or the fact I'm syncing all this data every time an action is dispatched

**Comment by hardchor** [comment]
That's good to hear. I'm hoping that `electron-redux` would be easy enough to implement without the timesheets repo. Let me know if something is amiss.

Storing data of that size in memory (redux store) will always cause issues. Since the store is being cloned every time you open a new window, that will multiply and almost certainly affect performance of your app. If you use the same persistence method like https://github.com/hardchor/timesheets/blob/master/app/main/index.js#L27, that'd also mean having to serialise the entire store and writing it to disk for every action. If you chose to stick with your current architecture, that'll almost certainly be a bottleneck.

I don't know what your app is or why you need to store that amount of data in your store, but there's probably a more performant solution that takes the load of your app and lets it breathe again ;)

**Comment by alexemorris** [comment]
Thanks for the reply! It was easy enough to implement but the time sheets repo certainly helped.

To summarise I'm preprocessing and index what's essentially a csv file into a redux store at load time which takes a few seconds.

The only place I'm using this data is in a preview component, the amount previewed is adjustable and the PreviewContainer only provides what is needed from the 'static' part of the store I previously mentioned. 

The preview component works well and seems fast, it's just with the whole dataset in the store, the Dev tools (specifically redux) seem to slow down significantly. I don't even know if this is a problem or not for the end user once it's built! But I certainly don't want to have to reindex and parse the data every time the user changes the amount of data they want to preview, or look at the next 100/1000 items!
