### ISSUE TITLE
Redux Promise Middleware doesn't seem to work in Renderer

### ISSUE THREAD

**Issue by hhff** [hardchor/electron-redux#13]
I'm using the https://github.com/pburtchaell/redux-promise-middleware with Redux.  He's my store config:

```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import { hashHistory } from 'react-router';
import { routerMiddleware, push } from 'react-router-redux';
import createLogger from 'redux-logger';
import promiseMiddleware from 'redux-promise-middleware';
import rootReducer from '../reducers';

import {
  forwardToRenderer,
  forwardToMain,
  triggerAlias,
  replayActionMain,
  replayActionRenderer,
  getInitialStateRenderer
} from 'electron-redux';

const actionCreators = {
  push,
};

const logger = createLogger({
  level: 'info',
  collapsed: true
});

const router = routerMiddleware(hashHistory);
const promise = promiseMiddleware();


export default function configureStore() {

  // If Redux DevTools Extension is installed use it, otherwise use Redux compose
  /* eslint-disable no-underscore-dangle */
  const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ?
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
      // Options: http://zalmoxisus.github.io/redux-devtools-extension/API/Arguments.html
      actionCreators,
    }) :
    compose;
  /* eslint-enable no-underscore-dangle */

  const enhancer = composeEnhancers(
    applyMiddleware(forwardToMain, router, thunk, promise, logger)
  );
  const initialState = getInitialStateRenderer();
  const store = createStore(rootReducer, initialState, enhancer);

  if (module.hot) {
    module.hot.accept('../reducers', () =>
      store.replaceReducer(require('../reducers')) // eslint-disable-line global-require
    );
  }

  replayActionRenderer(store);
  return store;
}

export function configureElectronStore(initialState: Object) {
  const enhancer = compose(
    applyMiddleware(triggerAlias, thunk, promise, forwardToRenderer)
  );
  const store = createStore(rootReducer, initialState, enhancer);
  replayActionMain(store);
  return store;
}
```

Redux Promise Middleware works great with actions that are fired from the main process (it wraps actions with promise payloads as `_PENDING` & `_FULFILLED` / `_REJECTED`)

However - when I call the same action from within the renderer, those promise edges are not applied to the action flow.  I'm instantiating the store with promise in both environments, so I'm not sure what's going on.  Should I be putting `promise` before `forwardToMain` for the renderer store in this case?

**Comment by hhff** [comment]
Hmmm, so I've decided to only send actions to redux via IPC 
```
renderer ---IPC---> main.js --- Redux ---> main store --- replayToRenderer ---> renderer store
```

The main problem I was having when using `triggerAlias` (another approach I tried) was that I was sending an instantiated javascript class, that was having it's methods stripped off it.  Keeping everything in the main.js thread (this app is mostly a background process) is a more sane approach in my case.

I'm leaving this open for now @hardchor, as this problem still persists, but I've solved it in my case by simply not dispatching from the renderer

**Comment by hardchor** [comment]
Sorry, only just got back from abroad.

Can you post an example of how you were trying to trigger actions on the renderer side?

**Comment by hardchor** [comment]
Also check out https://github.com/hardchor/electron-redux/issues/11#issuecomment-258403957 for a working example

**Comment by burkhardr** [comment]
@hhff Has this solved your issue?

**Comment by hhff** [comment]
I didn't get this specific problem working, but only firing redux actions from my main electron app is a sane work around.  Happy to close for now!
