### ISSUE TITLE
Will electron-redux support type checking？

### ISSUE THREAD

**Issue by ervinewell** [hardchor/electron-redux#133]
**Is your feature request related to a problem? Please describe.**
In my circumstance, action.payload might be Map or Set or non-plain object which is supported in redux. While transporting between processes, these datas will be lost, even cause a block or crash.

**Describe the solution you'd like**
Support all the datatype(seems impossible).

**Describe alternatives you've considered**
Check action.payload before transporting.

**Comment by hardchor** [comment]
Good news! This has been introduced in `1.5.1` 🥳
