### ISSUE TITLE
Can I expect to improve performance by using this?

### ISSUE THREAD

**Issue by corock** [hardchor/electron-redux#136]
Hello :)

I currently developed web-based apps with `React`.
As I wanna boost high-performing app regarding performance issue,

I choose to convert `React` apps into `Electron`.
And I discovered `electron-redux` released this repo, and I wonder is it available benefits by introducing `electron-redux`.

**Comment by hardchor** [comment]
Hey! Is this unlikely to fix (or introduce, for that matter) any performance issues.
