### ISSUE TITLE
Integration with redux-api?

### ISSUE THREAD

**Issue by rdiazv** [hardchor/electron-redux#26]
Hi, first of all, great library! :)
My app is using `redux-api` and right now the only thing that I can't figure out is how to avoid duplicated requests on the renderer and main.

I should be using `createAliasedAction` to make the actions fire on the main process only, but `redux-api` auto generates the action creators... any advice??

**Comment by burkhardr** [comment]
> Hi, first of all, great library! :)
Thanks 😄 

>My app is using redux-api and right now the only thing that I can't figure out is how to avoid duplicated requests on the renderer and main.
I'm not quite sure how `redux-api` works. I've used https://github.com/hardchor/timesheets in the past to demo integration with different libraries, e.g. https://github.com/hardchor/timesheets/pull/211 .
As a bit of background, the `forwardToMain` and `forwardToRenderer` middleware should already take care of that for you. It adds meta data to each action that basically tells each side where it came from and whether it should be forwarded.

> I should be using createAliasedAction to make the actions fire on the main process only, but redux-api auto generates the action creators... any advice??
So `redux-api` just creates actions on the fly? Is there any way to hook in to the action creators?
`createAliasedAction`

**Comment by rdiazv** [comment]
Thanks for your answer. There is no way to customize the actions creators 😞 ... I will try to solve my problem with a different pattern.

**Comment by burkhardr** [comment]
Things like redux-api (or redux-saga) look nice at first, but they also take a lot of flexibility away from you.
I had a look through their source code. One possible solution I could see is to register your own middleware (it's not too hard, take a look at https://github.com/hardchor/electron-redux/blob/master/src/middleware/forwardToRenderer.js) that intercepts any redux-api actions (they seem to be namespaced) and apply `createAliasedAction` before re-firing it.
