### ISSUE TITLE
Error when using with angular-redux/store

### ISSUE THREAD

**Issue by jaypanares** [hardchor/electron-redux#36]
Hi,

Currently using your library with angular-redux/store and I'm getting the following error when implementing:

![image](https://user-images.githubusercontent.com/7044596/27316133-3faa39a2-55b0-11e7-9108-8f72c6fcabed.png)

Not sure if middleware is implemented differently in angular-redux/store.  I hope you can help me out on this one.

Thanks!

**Comment by burkhardr** [comment]
Hey @jaypanares ,

It's unlikely this has to do with either. You're trying to require `fs` (a node module) through webpack, so will likely need a shim. A quick google search surfaced this: https://stackoverflow.com/a/39249719/495771

**Comment by hardchor** [comment]
Unfortunately not heard back from you @jaypanares, so closing this for now. Feel free to comment and we'll get back on it.

**Comment by hardchor** [comment]
I just published `1.5.1`. This might fix the issue.

**Comment by m4rkus** [comment]
I have the same problem. It is related to` require('electron')` inside forwardToMain.js. [This article explains the dilemma.](https://dev.to/michaeljota/integrating-an-angular-cli-application-with-electron---the-ipc-4m18)
Is there any way to work around this?

**Comment by m4rkus** [comment]
My bad, I tried 1.5.4 and thought the 1.5.1 fix referenced above was included. Downgrading to 1.5.1 solves the problem for me.
