### ISSUE TITLE
Provide easy way to init store

### ISSUE THREAD

**Issue by hardchor** [hardchor/electron-redux#4]

**Comment by rsaccon** [comment]
It looks to me that if using `getInitialStateRender` in the renderer process, than we have explicitly to set the initial state at the main process as global variable `reduxState`, however I couldnt find this documented anywhere, except in the source code itself

**Comment by hardchor** [comment]
Hey @rsaccon . That's already happening in https://github.com/hardchor/electron-redux/blob/master/src/helpers/replayActionMain.js#L5-L8, so a manual step shouldn't be necessary? Are you having trouble getting the renderer store initialised?

**Comment by rsaccon** [comment]
Ok, thanks, I guess now all is clear, I just set optionally the initialState at main to some value and use `getInitialStateRenderer`  at renderer. Thanks again.

**Comment by hardchor** [comment]
No worries, please let me know if the docs need to be a bit clearer in that respect.

**Comment by hardchor** [comment]
No worries, please let me know if the docs need to be a bit more clear in
that respect
