### ISSUE TITLE
Integration to electron-react-boilerplate

### ISSUE THREAD

**Issue by mtompkins** [hardchor/electron-redux#43]
Greetings~

I'm trying to implement your approach into a fork of the [electron-react-boilerplate](https://github.com/mtompkins/electron-react-boilerplate) to which I've added a 2nd renderer. This seems a natural use case for your solution. I'm having quite a bit a difficulty, so much so that sort of asking for a help on any given error isn't reasonable. I've cleaned the public fork so my efforts aren't muddling the base.

In the event you are feeling the spirit/willingness to help, I'd welcome some guidance on how to go about it within the boilerplate which I'm offering back up as a template to the fork's source.

As the author I was thinking it might be something you can do with a few minutes of effort. If so I'd appreciate the assist and I hope you understand :) If not - no worries - I'll stumble until I get there. 

Many thanks,
Mark

**Comment by hardchor** [comment]
Hey Mark! 

Great to hear about your project. I'm on holidays for the next 3 weeks with limited access to Internet and laptop (on my phone right now), so not sure how much help I can be. Did you have a look at the timesheet repo linked in the readme? That should give you a good starting point!

**Comment by mtompkins** [comment]
Thanks for taking the time to respond and here's wishing you an enjoyable time away.

I have tried to examine your timesheet repo, however it does not compile in its current state (at least on linux) adding to my challenge which is why after a couple weeks of trying I thought I'd reach out. Perhaps when you return I'll be able to post some specific roadblock(s) and you'll be able to comment - or I'll have sorted it
 out directly. 

Good luck!

**Comment by mtompkins** [comment]
Just a quick follow-up ... I've made solid progress and now have what appears to be a single "issue" which is great. Using the boilerplate with no changes outside of incorporating your solution, on triggering the counter the renderer store seems to get thrown twice and the main thread store only once (as expected). I've probably missed something in the reducers or such that I'll continue to investigate.

I've spun this up here during trial: https://github.com/mtompkins/electron-react-boilerplate/tree/second-renderer-shared-store

**Comment by mtompkins** [comment]
The thread / link to [thunk-actions](https://github.com/hardchor/timesheets/tree/thunk-actions%239/app/shared/actions) was exactly what I needed. Thank you for having that somewhere within your repo.  I would make the suggestion of making that more discoverable / or referencing it in perhaps a link or wiki for future visitors, especially coming from the boilerplate.

Thanks again for sharing your work and hopefully an enjoyable holiday!
