### ISSUE TITLE
Typescript declaration file

### ISSUE THREAD

**Issue by dyst5422** [hardchor/electron-redux#44]
Should add a TypeScript declaration file to DefinitivelyTyped, especially considering the usefulness of static typing on the large apps that electron enables.

**Comment by hardchor** [comment]
I  don't use typescript, so wouldn't even know where to start. Can you help out?

**Comment by dyst5422** [comment]
Yes. I'm on vacation this week, but I'll see if I can draft something up in the next couple of weeks for review here.

**Comment by hardchor** [comment]
@dyst5422 If you're still interested in this, please feel free to raise a PR. I hope you had a great time on vacation!

**Comment by adammenges** [comment]
@dyst5422 I'm guessing you didn't get around to this?

```
⇒  npm install @types/electron-redux
npm ERR! code E404
npm ERR! 404 Not Found: @types/electron-redux@latest
```

**Comment by dyst5422** [comment]
@adammenges 

Not even a little bit. We dropped our use of Redux as a whole as it is far overbuilt for our use case (especially when using the new context api and typescript).
