### ISSUE TITLE
Aliased actions and relative paths

### ISSUE THREAD

**Issue by mtompkins** [hardchor/electron-redux#45]
I'm trying to think through how to handle the following:   

We agree that remote calls (e.g. database) should be handled exclusively in the main thread. Using [aliased actions](https://github.com/hardchor/electron-redux#aliased-actions-main-process) is there to help.  However, what if there are credentials necessary for that call? These credentials shouldn't be exposed to the `renderer thread`, however, that is where the request originates and maps the relative paths using `createAliasedAction()` in my testing.

So with some sloppy code example:

`main thread - dbCred.js`
```
// @flow
import fs from 'fs';
import path from 'path';
import { app } from 'electron';

//
// ─── IMPORT CERTIFICATES ────────────────────────────────────────────────────────
//
const appPath = process.env.NODE_ENV === 'production' ? app.getAppPath() : path.join(__dirname, '..', '..');
export const cKey = fs.readFileSync(path.join(appPath, 'main/certs/client-key.pem'));
export const cCert = fs.readFileSync(path.join(appPath, 'main/certs/client-cert.pem'));
export const cCA = fs.readFileSync(path.join(appPath, 'main/certs/ca-cert.pem'));
```

`main thread - database.js`
```
import Sequelize from 'sequelize';
import { dbCredentials, cKey, cCert, cCA } from './dbCred';
import { mapQry } from './queries';

// Instantiate model connection using Sequelize
const sequelize =
  new Sequelize(dbCredentials.database, dbCredentials.user, dbCredentials.password, {
    host: dbCredentials.host,
    dialect: 'mysql',
    dialectOptions: {
      ssl: {
        key: cKey,
        cert: cCert,
        ca: cCA
      }
    },
    pool: {
      max: 5,
      min: 0,
      idle: 10000
    },
  });
...
```
`renderer thread - get-records-creators.js`
```
import { createAliasedAction } from 'electron-redux';
// Action Types
import { FETCH_QUERY, FETCH_RECORD_DISPOSE, TOGGLE_DISPOSE } from '../../shared/constants/ActionTypes';
import { sequelizeQry } from '../../main/sql/database';

/** Action-creators */
export default function fetchRecords(qryName: string) {
  const actionType = FETCH_QUERY;

  if (qryName === 'DISPOSE') {
    return (dispatch: *) => {
      dispatch({
        type: `${actionType}_DISPOSE`
      });
      // Also clear activeRecord
      dispatch({ type: FETCH_RECORD_DISPOSE });
      // ... and clear any selected items from store
      dispatch({ type: TOGGLE_DISPOSE });
    };
  }

  return (dispatch: *) => {
    dispatch({ type: `${actionType}_PENDING` });
  // Converted to ALIAS for testing ...
    createAliasedAction(
      actionType,
      () => ({
        type: actionType,
        payload: sequelizeQry(qryName)
          // Convert to ALIAS?
          .then(
          (payload) => dispatch({ type: 'FETCH_QUERY_FULFILLED', payload })
          )
          // Convert to ALIAS?
          .catch((error) => dispatch({ type: 'FETCH_QUERY_REJECTED', error }))
      })
    );
  };
}
```

With the above code I'm initiating from the `renderer side` a database call with `Sequelize` which is Promised based and using `createAliasedAction` to execute purely in the `main thread` with the needed credentials as to my understanding of how it works.  (Note: I've not worried about the returns from the Promise yet)

I've called this structure purely with IPC and it works as expected, but then of course the request to `Sequelize` initialized in effect from the `main thread` based on the listener.

I'd welcome a bit of a nudge on how to accomplish this.

Many thanks!

**Comment by mtompkins** [comment]
I've decided to go another direction so I am closing this ticket.
I do believe, however, that the issue remains. 

Good luck!

**Comment by burkhardr** [comment]
Hey,

Sorry for the late reply, I'm currently on vacation. Without being able to further read into your code or test this out myself - what is your concern in sending the credentials across? Is it purely a security concern (there should be none) or is it because of the payload size?

Thanks,
Burkhard
