### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by okonet** [hardchor/electron-redux#48]
Changelog is a great way to keep users informed of changes you've made in the library. I've readin trough commits 90% of which aren't library source code related. Please consider adding changelog or switch to semantic-release with an appropriate commit naming scheme. This would help significantly. 

Thanks!

**Comment by burkhardr** [comment]
Hey @okonet,

I don't usually release until after a significant change (i.e. library code update / new features or BC of 3rd party libs). As of now, I've not had the need for a change log and/or upgrading instructions as there were no breaking changes so far, but will take a look at compiling one for the next release.

Thanks for your feedback! 😄
