### ISSUE TITLE
Use SemVer

### ISSUE THREAD

**Issue by okonet** [hardchor/electron-redux#49]
I've just discovered that v1.2.6 introduced a breaking change compared to v1.2.5 in this commit: https://github.com/hardchor/electron-redux/commit/e4b39387fd430292ec2e36264e3aaef4e29202d4. 

Being marked as a patch it was safe to update but this broke the behavior of my app. 

Needless to say that it is not in sync with docs:

> To stop an action from propagating from renderer to main store, simply set the scope to local:

but this is the default behavior now.

Using SemVer would mean this would be released as a major version keeping users of prior version in safety from breakage.

Please consider using SemVer when releasing new versions!

And thanks for the great library! 👍

**Comment by okonet** [comment]
Sorry I must have been confused by this commit. The werid part is that I see that my actions are issues with `scope: 'local` by default and I'm not sure where it's coming from.

**Comment by okonet** [comment]
I just realized that Redux DevTool extension is seeing the modified actions. This made me think that my original actions were modified. Sorry for the confusion. 🙏

**Comment by burkhardr** [comment]
No worries ;) Glad you managed to track your issue down!
