### ISSUE TITLE
Cannot store MediaDeviceInfo objects

### ISSUE THREAD

**Issue by derwaldgeist** [hardchor/electron-redux#50]
First off, thanks for the great package. I'm using it success since a couple of months without any issues. Today I ran into the following problem: I wanted to store an array of `MediaDeviceInfo` objects as it is returned by `navigator.mediaDevices.enumerateDevices()`.

Inside the `action` creator method, the array elements are still valid `MediaDeviceInfo` objects. But as soon as I pass this action to `dispatch()`, only the structure of the array remains. The `MediaDeviceInfo` objects, however, appear als standard JavaScript objects without any properties.

Does electron-redux only support plain JavaScript objects as action payloads?

**Comment by hardchor** [comment]
Hey @derwaldgeist 

Great to hear you're enjoying the module! The short and simple is: yes, they need to be POJOs, arrays or primitives.

The reason for that being that we need to serialise the payload before we send it over the wire (i.e. to the main process, where it gets deserialised and fanned out to all the other stores). The FSA-validation should've caught your use-case (not sure why it didn't...) - see https://github.com/acdlite/flux-standard-action#actions.

**Comment by derwaldgeist** [comment]
Hi @hardchor Thanks for the clarification. So it is not sufficient that the payload is FSA-compliant, right? Think it would be good if this was mentioned in the docs somewhere. I solved it now by copying the values of the MediaDeviceInfo objects into a POJO -- that worked.

**Comment by burkhardr** [comment]
You are right, I misread the specs. It does indeed state that the payload itself can be of ANY type. This is going to cause issues when, e.g. sending an `Error` object (or a `MediaDeviceInfo` as in your case).
I'll add some notes to the readme.

**Comment by derwaldgeist** [comment]
Cool, thanks, makes sense!
