### ISSUE TITLE
Action containing a map in the payload is badly serialized

### ISSUE THREAD

**Issue by eric-burel** [hardchor/electron-redux#54]
Hi,

It seems that when the payload of an action triggered in the renderer contains a js `Map`, it is somehow converted as an object when using `electron-redux` before it reaches the reducer (actually even before it reaches any other middleware according to `redux-logger`).

I guess this is related to ipc serialization ? 

Note that I use an `immutable` state, but I don't think it is related, I use a native Map for my object, not an immutable one.

**Comment by hardchor** [comment]
Hi @eric-burel 

You are completely right, it has to do with serialisation. Unfortunately, there's no reliable way to serialise (and unserialise at the other end) payloads that are not POJOs / arrays / primitives.

In fact, I'd added a to-do to https://github.com/hardchor/electron-redux/projects/1 to document that restriction but haven't had the time to do so yet.

**Comment by hardchor** [comment]
P.S.: You are right, the state itself can be of any form and shape you like (so immutable is fine), but the payload itself is restricted to POJOs/arrays/primitives.

**Comment by hardchor** [comment]
Let me know if https://github.com/hardchor/electron-redux/pull/56/files#diff-04c6e90faac2675aa89e2176d2eec7d8 makes sense to you.

**Comment by eric-burel** [comment]
Hi, thanks for this quick answer. I'll be a bit more specific in the doc about what it excludes, saying something like "This exclude native JavaScript or DOM objects like FilesForm, Map, classes and so one"
I'll try to take a look at how ipc works, because in a full JavaScript environment we would except a far better serialization, I'll link to the relevant issue from the electron repo if necessary.

**Comment by burkhardr** [comment]
@eric-burel Our middleware is simply bypassed when we encounter a local action (see https://github.com/hardchor/electron-redux/blob/master/src/middleware/forwardToMain.js#L13), so won't reach the main store in the first place - is that what you meant?

Re: the blurb about what is and isn't supported - is mentioning "POJOs only" not enough? I'm happy to add a little more explanation if it helps to avoid confusion.

**Comment by eric-burel** [comment]
@burkhardr Hi, the doc is great now, thanks !

What I meant is that the serialized action I am talking about was actually a local action, therefore I don't fully understand why it has been serialized in the first place.

**Comment by hardchor** [comment]
Hmm no you are right, that shouldn't have happened. Can you post an example of the action in question?
