### ISSUE TITLE
Freezes on empty action payload

### ISSUE THREAD

**Issue by eric-burel** [hardchor/electron-redux#57]
Hi,

This one is weird. When using an action creator with an empty payload created using `redux-actions`, the application badly fails and freezes.

```js
import { createAction } from 'redux-actions';
// dispatching this will freeze the app
const myEmtpyPayloadAction = createAction('HI');
```
No payload field is still FSA-compliant, so this should'n't happen. I can't tell where this freeze however.

**Comment by hardchor** [comment]
Hey,

Thanks for the bug report. I'm on the road at the moment, but will take a look as soon as I'm home (or early next week at the latest).

**Comment by liederivative** [comment]
@eric-burel @hardchor any update about this ?

**Comment by hardchor** [comment]
Thanks for the input! Feel free to reopen if @biggyspender's hint didn't work for you.
