### ISSUE TITLE
Actions are not being forwarded from the render to main

### ISSUE THREAD

**Issue by walleXD** [hardchor/electron-redux#63]
Hi,

I have everything setup but there's a small hitch and after a few hours of digging, I am not sure why this is happening! My redux store is setup in both the main and renderer threads and the main store is able to successfully communicate with the store in the renderer but the actions dispatched in the renderer doesn't get back to the store in the main thread. 

``` es6
// Shared store init
import { createStore, applyMiddleware } from 'redux'
import promise from 'redux-promise'
import thunk from 'redux-thunk'
import reducers from '../reducers'

const isDev = process.env.NODE_ENV !== 'production'

export default (
  preloadedState = {},
  injectMiddleware = undefined,
  injectReducer = undefined
) => {
  const prodMiddlewares = [
    promise,
    thunk
  ]

  const devMiddlewares = [
    require('redux-immutable-state-invariant').default()
  ]

  let middlewares = isDev
    ? [...devMiddlewares, ...prodMiddlewares]
    : prodMiddlewares

  if (injectMiddleware) middlewares = injectMiddleware(middlewares)

  const { composeWithDevTools } = process.type !== 'renderer'
    ? require('remote-redux-devtools')
    : require('redux-devtools-extension')

  const store = createStore(
    reducers(injectReducer),
    preloadedState,
    composeWithDevTools(
      applyMiddleware(...middlewares)
    )
  )

  if (module.hot) {
    module.hot.accept('../reducers/', () => {
      const nextReducer = require('../reducers/index').default
      store.replaceReducer(nextReducer)
    })
  }

  return store
} 
```

```es6
// renderer store
import initStore from '../../common/lib/initRedux'
import { routerMiddleware } from 'react-router-redux'
import { forwardToMain, getInitialStateRenderer } from 'electron-redux'

import history from './history'

const isDev = process.env.NODE_ENV !== 'production'

export default initStore(
  getInitialStateRenderer(),
  middleware => {
    if (isDev) {
      middleware.push(
        require('redux-logger').createLogger()
      )
    }
    return [
      forwardToMain,
      routerMiddleware(history),
      ...middleware
    ]
  }
)
```

```es6
// main store
import { forwardToRenderer, triggerAlias } from 'electron-redux'
import initStore from '../../common/lib/initRedux'

const isDev = process.env.NODE_ENV !== 'production'

export default initStore(
  undefined,
  middleware => {
    if (isDev) {
      middleware.push(
        require('redux-node-logger')()
      )
    }
    return [
      triggerAlias,
      ...middleware,
      forwardToRenderer
    ]
  }
)
```

I am also using redux actions to make sure all my actions are FSA compliant and here's a simple example:
```es6
import { createAction, handleActions, combineActions } from 'redux-actions'

export const increment = createAction(
  '@@example/INCREMENT'
)

export const decrement = createAction(
  '@@example/DECREMENT',
  i => -i
)

export default handleActions({
  [combineActions(increment, decrement)]: (state, { payload }) => ({
    ...state, score: state.score + payload
  })
}, {score: 0})

```
Given that actions are being successfully forwarded from the main to the renderer thread, my guess would be that the issue is isolated to something in the renderer but not sure where it's going wrong. Thanks in advance for all help and the awesome library!

EDIT: did a little bit more digging and it seems no IPC call is being made from the renderer but the same actions lead to IPC calls from the main thread

**Comment by hardchor** [comment]
Hey @walleXD 

The issue will most likely lie [here](https://github.com/hardchor/electron-redux/blob/master/src/middleware/forwardToMain.js#L8). The reason why that line is there is that most libraries use the `@@` prefix to namespace their actions (and so does the `@@INIT` action), and you don't want them to be propagated throughout the processes. Try removing the `@@` prefix and let me know if that works for you.

It might indeed be helpful to document that restriction.

**Comment by hardchor** [comment]
@walleXD Yes, of course I am! Go ahead.

I'd be interested in how you're using the react-router-redux actions from the renderer in the main thread. Can you go into a little more detail?

**Comment by walleXD** [comment]
@hardchor I am trying to use the redux store on the main thread as the central data hub and using redux-persist to store the state when the app closes. Every time when the app window is closed, its not possible to restore it back to the same page/location as the `react-router-redux` reducer's actions are ignored. Also, by using `react-router-redux` from the main thread, it would be possible to respond to user actions on the renderer from the main thread. At the end of the day I am trying to use `electron-redux` as  abstraction over IPC and making sure to use only renderer specific features as this would make it easy to port (react) web apps more easily into full fledged web apps to the other way around as the only thing that would need to be ported/tweaked are redux actions

**Comment by walleXD** [comment]
@hardchor I am struggling to get aliased actions to work from the renderer as my app just freezes and while digging around with the debugger, react seems to fail silently. I am trying fire the above actions to test things out:

```es6
// example reducer
import { createAction, handleActions, combineActions } from 'redux-actions'
import { createAliasedAction } from 'electron-redux'

export const increment = createAction(
  'example/INCREMENT'
)

export const decrement = createAction(
  'example/DECREMENT',
  i => -i
)

export const _increment = createAliasedAction(
  'example/INCREMENT',
  payload => increment(payload)
)

export default handleActions({
  [combineActions(increment, decrement)]: (state, { payload }) => {
    if (state.score) return {...state, score: state.score + payload}
    else return {...state, score: payload}
  }
}, {score: 0})
```

Any ideas on why it's failing?
