### ISSUE TITLE
how can I get resolved value when I call alias action

### ISSUE THREAD

**Issue by dingchaoyan1983** [hardchor/electron-redux#68]
I want to move my state management from render process to main process, but I have a problem that is 
I have a api request action which return a promise. the pseudo code is like this
```
dispatch(readProfile({
  type: 'READ_PROFILE',
  payload: readProfilePromise
})).then(() => blabla);
``` 
this is works fine,

now I want to move this api request to main process, according to the api doc in `electron-redux`, I should use alias action creator, the main process and render process communicate with `ipc` which is a event system, I can't get the promise any more, but I don't want to modify the current code, because there are too much stuff to change, is there any suggestions for this problem, thanks in advance.

**Comment by hardchor** [comment]
Hi @dingchaoyan1983 

Sorry, I'm finding it hard to understand what you're trying to achieve. You can't get the promise anymore?

The purpose behind aliased actions is that async actions (e.g. promises) are handled in a single place. Once resolved, promises usually trigger a success/error action (see https://github.com/acdlite/redux-promise) on the main thread, which would then get fanned out to the renderer processes.

**Comment by hardchor** [comment]
Happy to re-open if you reply.
