### ISSUE TITLE
Minimalist example (or more documentation) needed

### ISSUE THREAD

**Issue by aendrew** [hardchor/electron-redux#80]
Hi there,

I've been fighting against the Timesheets example all morning and am still not entirely sure what I'm doing (particularly with regards to React Router — Timesheets seems to use v3, and the project I'm trying to add electron-redux to is v4).

To this end, it might be really useful to have a more minimalist example than Timesheets (especially one updated to use React Router 4). Some updated docs on how exactly aliased actions work would be most helpful. Happy to contribute if you think it'd be useful.

**Comment by hardchor** [comment]
Hey! Since this received a lot of votes, you're definitely not alone :)

An extremely minimalist example is actually the integration test in this monorepo (https://github.com/hardchor/electron-redux/tree/master/packages/electron-redux-e2e). Let me know if that helps!
