### ISSUE TITLE
Redux-Observable and Typed Actions

### ISSUE THREAD

**Issue by ysfjwd** [hardchor/electron-redux#82]
I come from an ngrx background and quite used to the ngrx way of using typed actions.

i.e.

    export class RestoreWindowState implements FluxStandardAction {
      public readonly type = windowActionTypes.WINDOW_RESTORE_STATE;
    
      constructor(public payload: IWindowState) {}
    }

where FluxStandardAction Looks like this

    export interface FluxStandardAction {
      type: string;
      payload?: any;
      error?: boolean;
      meta?: any;
    }

I wrote a custom middleware to convert ```new windowActions.RestoreWindowState(state)``` to a plain object. Here is what my middleware looks like.

    export const actionToPlainObjectMiddleware = store => next => action => {
      if (typeof action === 'object' && action.type) {
        const toForward = { ...action };
        return next(toForward);
      } else {
        throw new Error('Action must be FSA');
      }
    };

now if i do

    const loadWindowStateFromStorageEpic = action$ =>
      action$.ofType(windowActionTypes.WINDOW_LOAD_STATE_FROM_STORAGE).pipe(
        mapTo(() => {
          const windowState = WindowStateKeeper.load('main');
          return new windowActions.RestoreWindowState(windowState);
        }),
      );

i get

```Error: Action must be FSA```

Fine, I am not getting an object at my custom middle, so what I am getting? its a `function`. Here is my middleware declaration.

const epicsMiddleware = createEpicMiddleware(windowEpics);

```
export const store = createStore(
  windowStateReducer,
  applyMiddleware(actionToPlainObjectMiddleware, epicsMiddleware, forwardToRenderer),
);
```

What am i doing wrong?

**Comment by ysfjwd** [comment]
my bad. false negative here.

**Comment by hardchor** [comment]
APologies for the late reply. Could you elaborate where you went wrong?

**Comment by ysfjwd** [comment]
@hardchor it was a false negative, i needed to use `map` instead of `mapTo`, see https://stackoverflow.com/questions/48618526/electron-redux-typescript-redux-observable-and-typed-actions/48631023?noredirect=1#comment84346380_48631023 :)
