### ISSUE TITLE
Why are renderer @@ actions silently blocked from sending to main?

### ISSUE THREAD

**Issue by ylg** [hardchor/electron-redux#84]
at-at-source/action seems a pretty common convention for naming actions. Nearly every action in the app I've just added to electron-redux is being blocked, so we'd have to do something pretty fancy with rewriting names or fork electron-redux. Perhaps @@ has come to mean something special?

**Comment by hardchor** [comment]
Hi,

IIRC, the @@ prefix came from react router redux. Propagating navigation events (amongst others) caused unexpected side effects at the time. I agree that it might not be a good idea to block all @@ actions. A whitelist (or blacklist) option might be a good idea.

**Comment by ylg** [comment]
That makes sense. In our case, it looks like we might want router actions propagated as well (though main would likely have a different reducer hooked up than the renderers) But, I know we've other third party libs that name @@ and our own SPA-supporting libs do that as well. If the blocking rules can be changed by the lib user, e.g., via a blacklist, then what they are out of the box is less exciting. 

To KISS, perhaps either have no rules in electron-redux other than that was absolutely must be blocked to prevent forest fires in minimal apps, e.g., blocking non-FSA actions, or to have user configurable regex or array of regexes. Since there is already checking for meta.scope, which gives us (users) a way to stop propagation, I'd think the former would be the way to go since we (users). Perhaps combine that with an doc example of middleware regexing action names and conditionally applying meta.scope = "local"?
