### ISSUE TITLE
By default, all my actions are local?

### ISSUE THREAD

**Issue by wandonye** [hardchor/electron-redux#89]
My actions are defined like this:

```
export function setNewSession() {
  return {
    type: ON_NEW_SESSION
  };
}

export function onAdd(key: string) {
  return {
    type: ON_ADD_TAG,
    payload: key
  };
}
```

When I look at the console, every action has `meta : {scope: "local"}`. Is this normal?

I'm trying to figure this out because my Redux State is behaving weirdly since I followed [this](https://github.com/chentsulin/electron-react-boilerplate/pull/1615) to add some function to my menu. For example, my editor box is supposed to be empty, but it shows some text...

**Comment by hardchor** [comment]
Hey. The local scope is being set by https://github.com/hardchor/electron-redux/blob/master/packages/electron-redux/src/middleware/forwardToRenderer.js#L14 in the main store, and is just being used to avoid endless loops. That means though that your actions actually made it to the main store, so your issue might lie somewhere else.
