### ISSUE TITLE
Importing on renderer throws error

### ISSUE THREAD

**Issue by afresquet** [hardchor/electron-redux#96]
**Describe the bug**
Importing middleware and helpers from the library on the renderer process throws an error "TypeError: fs.existsSync is not a function".

**To Reproduce**
1. Setup an Electron app.
2. Setup React for the renderer process.
3. Copy the electron-redux setup code.
4. Error is thrown.

**Expected behavior**
I would expect the app to behave normally, when I remove the imports everything works correctly.

**Screenshots**
![](https://i.imgur.com/JqVRtuf.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave

**Comment by bettse** [comment]
Any details on how you solved this?

**Comment by hardchor** [comment]
@afresquet @bettse I just published `1.5.1`. Could you check if that fixes your issue?

**Comment by afresquet** [comment]
I don't have the project anymore and I don't really remember much about it since it's been a while, sorry :(
