### ISSUE TITLE
upgrade redux to ^4.0.0

### ISSUE THREAD

**Issue by hrishabhkumar** [hardchor/electron-redux#99]
**Is your feature request related to a problem? Please describe.**
No, I am getting a warning that it is compatible with ^3.4.0 but I am using redux ^4.0.0

**Describe the solution you'd like**
upgrade peer dependency of redux to ^4.0.0

**Comment by hardchor** [comment]
Hey @hrishabhkumar! Thanks for the report. Feel free to open a PR with the change :)

**Comment by tvainio** [comment]
This seems to be fixed in master already in July.  @hardchor would it be possible to release a new version with this change included? Thanks!

**Comment by hardchor** [comment]
Sorry about the massive delay! `1.5.1` released with all updates since then
